# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR="1.0"

[font]
size = 20.0

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.offset]
x = -1
y = 0

[scrolling]
history = 1000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.99
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

# [keyboard]
# bindings = [
#     { key = 'M', mods = 'Control', chars = '<Control>-M' },
# ]
